### ISSUE TITLE
Create a catalog 

### ISSUE THREAD

**Issue by SolMendiola** [xmartlabs/flutter-template#186]
Create a catalog with the design components:

- [x] Create catalog package, including base structure (#190)
- [x]  Add colors and text styles to catalog (#193) 
- [x] Add button catalog section (#195)
- [x] Add textfield catalog section (#197)
- [x] Add dialogs catalog section (#197)
- [x] Add selection controls catalog section (#197)
- [x] Write README (#201)
- [x] Add theme extension (#203)
